// <auto-generated />
using System;
using ClassifiedAds.Modules.TestGeneration.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassifiedAds.Migrator.Migrations.TestGeneration
{
    [DbContext(typeof(TestGenerationDbContext))]
    [Migration("20260219061423_AddTestSuiteSelectedEndpointIds")]
    partial class AddTestSuiteSelectedEndpointIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("testgen")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Log")
                        .HasColumnType("text");

                    b.Property<string>("ObjectId")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLogEntries", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActivityId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("ObjectId")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TriggeredById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomOrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DependsOnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrderCustomized")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DependsOnId");

                    b.HasIndex("EndpointId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TestSuiteId", "CustomOrderIndex");

                    b.HasIndex("TestSuiteId", "OrderIndex");

                    b.ToTable("TestCases", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VersionAfterChange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType");

                    b.HasIndex("ChangedById");

                    b.HasIndex("CreatedDateTime");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestCaseChangeLogs", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseExpectation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BodyContains")
                        .HasColumnType("jsonb");

                    b.Property<string>("BodyNotContains")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedStatus")
                        .HasColumnType("jsonb");

                    b.Property<string>("HeaderChecks")
                        .HasColumnType("jsonb");

                    b.Property<string>("JsonPathChecks")
                        .HasColumnType("jsonb");

                    b.Property<int?>("MaxResponseTime")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseSchema")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId")
                        .IsUnique();

                    b.ToTable("TestCaseExpectations", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PathParams")
                        .HasColumnType("jsonb");

                    b.Property<string>("QueryParams")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId")
                        .IsUnique();

                    b.ToTable("TestCaseRequests", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("ExtractFrom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HeaderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("JsonPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Regex")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestCaseVariables", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestDataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestDataSets", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestOrderProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppliedOrder")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConsideredFactors")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProposalNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedOrder")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserModifiedOrder")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TestSuiteId", "ProposalNumber");

                    b.ToTable("TestOrderProposals", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ApiSpecId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GenerationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.PrimitiveCollection<string>("SelectedEndpointIds")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ApiSpecId");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("TestSuites", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuiteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApprovalStatusSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewState")
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviousState")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("TestCaseOrderSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType");

                    b.HasIndex("ChangedById");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TestSuiteId", "VersionNumber");

                    b.ToTable("TestSuiteVersions", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "DependsOn")
                        .WithMany()
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany("TestCases")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOn");

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseChangeLog", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseExpectation", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithOne("Expectation")
                        .HasForeignKey("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseExpectation", "TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequest", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithOne("Request")
                        .HasForeignKey("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequest", "TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseVariable", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("Variables")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestDataSet", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("DataSets")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestOrderProposal", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany("OrderProposals")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuiteVersion", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany("Versions")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("DataSets");

                    b.Navigation("Expectation");

                    b.Navigation("Request");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", b =>
                {
                    b.Navigation("OrderProposals");

                    b.Navigation("TestCases");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
