// <auto-generated />
using System;
using ClassifiedAds.Modules.TestGeneration.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassifiedAds.Migrator.Migrations.TestGeneration
{
    [DbContext(typeof(TestGenerationDbContext))]
    [Migration("20260502172902_SyncTestGenerationExpectedAssertionModels")]
    partial class SyncTestGenerationExpectedAssertionModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("testgen")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Log")
                        .HasColumnType("text");

                    b.Property<string>("ObjectId")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLogEntries", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.LlmSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AppliedTestCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CacheKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoveredRequirementIds")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LlmModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModifiedContent")
                        .HasColumnType("jsonb");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("SrsDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestedDescription")
                        .HasColumnType("text");

                    b.Property<string>("SuggestedExpectation")
                        .HasColumnType("jsonb");

                    b.Property<string>("SuggestedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SuggestedRequest")
                        .HasColumnType("jsonb");

                    b.Property<string>("SuggestedTags")
                        .HasColumnType("jsonb");

                    b.Property<string>("SuggestedVariables")
                        .HasColumnType("jsonb");

                    b.Property<string>("SuggestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppliedTestCaseId");

                    b.HasIndex("CacheKey");

                    b.HasIndex("DeletedById");

                    b.HasIndex("EndpointId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("TestSuiteId", "IsDeleted");

                    b.HasIndex("TestSuiteId", "ReviewStatus");

                    b.ToTable("LlmSuggestions", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.LlmSuggestionFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedbackSignal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackSignal");

                    b.HasIndex("SuggestionId", "UserId")
                        .IsUnique();

                    b.HasIndex("TestSuiteId", "EndpointId");

                    b.ToTable("LlmSuggestionFeedbacks", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActivityId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("ObjectId")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TriggeredById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsAnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RequirementsExtracted")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SrsDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriggeredById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QueuedAt");

                    b.HasIndex("SrsDocumentId");

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredById");

                    b.HasIndex("SrsDocumentId", "QueuedAt");

                    b.ToTable("SrsAnalysisJobs", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ParsedMarkdown")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawContent")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("StorageFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("ProjectId", "AnalysisStatus");

                    b.HasIndex("ProjectId", "IsDeleted");

                    b.ToTable("SrsDocuments", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Ambiguities")
                        .HasColumnType("jsonb");

                    b.Property<string>("Assumptions")
                        .HasColumnType("jsonb");

                    b.Property<float?>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("MappedEndpointPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float?>("RefinedConfidenceScore")
                        .HasColumnType("real");

                    b.Property<string>("RefinedConstraints")
                        .HasColumnType("jsonb");

                    b.Property<int>("RefinementRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("RequirementCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RequirementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SrsDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestableConstraints")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("SrsDocumentId");

                    b.HasIndex("SrsDocumentId", "DisplayOrder");

                    b.HasIndex("SrsDocumentId", "RequirementCode")
                        .IsUnique();

                    b.ToTable("SrsRequirements", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirementClarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AmbiguitySource")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AnsweredById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SrsRequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestedOptions")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredById");

                    b.HasIndex("SrsRequirementId");

                    b.HasIndex("SrsRequirementId", "DisplayOrder");

                    b.HasIndex("SrsRequirementId", "IsAnswered");

                    b.ToTable("SrsRequirementClarifications", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomOrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrderCustomized")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrimaryRequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("DeletedById");

                    b.HasIndex("EndpointId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("PrimaryRequirementId");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TestSuiteId", "CustomOrderIndex");

                    b.HasIndex("TestSuiteId", "IsDeleted");

                    b.HasIndex("TestSuiteId", "OrderIndex");

                    b.ToTable("TestCases", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VersionAfterChange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType");

                    b.HasIndex("ChangedById");

                    b.HasIndex("CreatedDateTime");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestCaseChangeLogs", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DependsOnTestCaseId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTestCaseId");

                    b.HasIndex("TestCaseId", "DependsOnTestCaseId")
                        .IsUnique();

                    b.ToTable("TestCaseDependencies", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseExpectation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BodyContains")
                        .HasColumnType("jsonb");

                    b.Property<string>("BodyNotContains")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectationSource")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedStatus")
                        .HasColumnType("jsonb");

                    b.Property<string>("HeaderChecks")
                        .HasColumnType("jsonb");

                    b.Property<string>("JsonPathChecks")
                        .HasColumnType("jsonb");

                    b.Property<int?>("MaxResponseTime")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrimaryRequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementCode")
                        .HasColumnType("text");

                    b.Property<string>("ResponseSchema")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId")
                        .IsUnique();

                    b.ToTable("TestCaseExpectations", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PathParams")
                        .HasColumnType("jsonb");

                    b.Property<string>("QueryParams")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Timeout")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId")
                        .IsUnique();

                    b.ToTable("TestCaseRequests", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequirementLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MappingRationale")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SrsRequirementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<float?>("TraceabilityScore")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SrsRequirementId");

                    b.HasIndex("TestCaseId", "SrsRequirementId")
                        .IsUnique();

                    b.ToTable("TestCaseRequirementLinks", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("ExtractFrom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HeaderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("JsonPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Regex")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestCaseVariables", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestDataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestDataSets", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("TestCasesGenerated")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriggeredById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QueuedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TriggeredById");

                    b.HasIndex("TestSuiteId", "QueuedAt");

                    b.ToTable("TestGenerationJobs", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestOrderProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppliedOrder")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConsideredFactors")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProposalNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedOrder")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserModifiedOrder")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TestSuiteId", "ProposalNumber");

                    b.ToTable("TestOrderProposals", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ApiSpecId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EndpointBusinessContexts")
                        .HasColumnType("jsonb");

                    b.Property<string>("GenerationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GlobalBusinessRules")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SelectedEndpointIds")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SrsDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ApiSpecId");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SrsDocumentId");

                    b.HasIndex("Status");

                    b.ToTable("TestSuites", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuiteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApprovalStatusSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewState")
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviousState")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("TestCaseOrderSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType");

                    b.HasIndex("ChangedById");

                    b.HasIndex("TestSuiteId");

                    b.HasIndex("TestSuiteId", "VersionNumber");

                    b.ToTable("TestSuiteVersions", "testgen");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.LlmSuggestion", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany()
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.LlmSuggestionFeedback", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.LlmSuggestion", "Suggestion")
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsAnalysisJob", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.SrsDocument", "SrsDocument")
                        .WithMany("AnalysisJobs")
                        .HasForeignKey("SrsDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SrsDocument");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirement", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.SrsDocument", "SrsDocument")
                        .WithMany("Requirements")
                        .HasForeignKey("SrsDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SrsDocument");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirementClarification", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirement", "SrsRequirement")
                        .WithMany("Clarifications")
                        .HasForeignKey("SrsRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SrsRequirement");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirement", null)
                        .WithMany()
                        .HasForeignKey("PrimaryRequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany("TestCases")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseChangeLog", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseDependency", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "DependsOnTestCase")
                        .WithMany()
                        .HasForeignKey("DependsOnTestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("Dependencies")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTestCase");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseExpectation", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithOne("Expectation")
                        .HasForeignKey("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseExpectation", "TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequest", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithOne("Request")
                        .HasForeignKey("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequest", "TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseRequirementLink", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirement", "SrsRequirement")
                        .WithMany("TestCaseLinks")
                        .HasForeignKey("SrsRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("RequirementLinks")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SrsRequirement");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCaseVariable", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("Variables")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestDataSet", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", "TestCase")
                        .WithMany("DataSets")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestGenerationJob", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany()
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestOrderProposal", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany("OrderProposals")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.SrsDocument", "SrsDocument")
                        .WithMany()
                        .HasForeignKey("SrsDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SrsDocument");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuiteVersion", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", "TestSuite")
                        .WithMany("Versions")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsDocument", b =>
                {
                    b.Navigation("AnalysisJobs");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.SrsRequirement", b =>
                {
                    b.Navigation("Clarifications");

                    b.Navigation("TestCaseLinks");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestCase", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("DataSets");

                    b.Navigation("Dependencies");

                    b.Navigation("Expectation");

                    b.Navigation("Request");

                    b.Navigation("RequirementLinks");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.TestGeneration.Entities.TestSuite", b =>
                {
                    b.Navigation("OrderProposals");

                    b.Navigation("TestCases");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
