// <auto-generated />
using System;
using ClassifiedAds.Modules.Identity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassifiedAds.Migrator.Migrations.Identity
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260405104242_UpdateRolePermissionMatrix")]
    partial class UpdateRolePermissionMatrix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedDateTime");

                    b.ToTable("PasswordHistories", "identity");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000001",
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000002",
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetRoles"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetRole"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddRole"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateRole"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteRole"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetUsers"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetUser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddUser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateUser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:SetPassword"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteUser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:SendResetPasswordEmail"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000013"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:SendConfirmationEmailAddressEmail"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000014"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AssignRole"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000015"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:RemoveRole"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000016"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:LockUser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000017"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UnlockUser"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000018"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetConfigurationEntries"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000019"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetConfigurationEntry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000020"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddConfigurationEntry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000021"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateConfigurationEntry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000022"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteConfigurationEntry"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000023"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:ExportConfigurationEntries"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000024"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:ImportConfigurationEntries"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000025"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetAuditLogs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000026"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetProjects"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000027"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000028"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000029"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000030"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:ArchiveProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000031"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetSpecifications"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000032"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000033"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000034"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000035"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:ActivateSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000036"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetEndpoints"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000037"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddEndpoint"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000038"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateEndpoint"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000039"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteEndpoint"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000040"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetFiles"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000041"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UploadFile"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000042"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetFile"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000043"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DownloadFile"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000044"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateFile"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000045"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteFile"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000046"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetFileAuditLogs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000047"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetTestSuites"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000048"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddTestSuite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000049"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateTestSuite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000050"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteTestSuite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000051"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:ProposeTestOrder"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000052"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetTestOrderProposal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000053"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:ReorderTestOrder"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000054"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:ApproveTestOrder"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000055"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GenerateTestCases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000056"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetTestCases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000057"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GenerateBoundaryNegativeTestCases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000058"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddTestCase"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000059"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateTestCase"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000060"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteTestCase"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000061"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetExecutionEnvironments"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000062"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddExecutionEnvironment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000063"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateExecutionEnvironment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000064"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeleteExecutionEnvironment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000065"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:StartTestRun"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000066"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetTestRuns"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000067"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetPlans"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000068"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddPlan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000069"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdatePlan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000070"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:DeletePlan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000071"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetPlanAuditLogs"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000072"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000073"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetCurrentSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000074"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000075"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000076"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:CancelSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000077"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetSubscriptionHistory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000078"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetPaymentTransactions"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000079"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:AddPaymentTransaction"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000080"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetUsageTracking"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000081"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:UpdateUsageTracking"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000082"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:CreateSubscriptionPayment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000083"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:GetPaymentIntent"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000084"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:CreatePayOsCheckout"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000085"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Permission",
                            Value = "Permission:SyncPayment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetProjects"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:AddProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:UpdateProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:DeleteProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:ArchiveProject"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetSpecifications"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:AddSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:UpdateSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:DeleteSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:ActivateSpecification"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000011"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetEndpoints"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000012"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:AddEndpoint"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000013"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:UpdateEndpoint"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000014"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:DeleteEndpoint"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000015"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetTestSuites"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000016"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:AddTestSuite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000017"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:UpdateTestSuite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000018"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:DeleteTestSuite"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000019"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:ProposeTestOrder"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000020"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetTestOrderProposal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000021"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:ReorderTestOrder"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000022"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:ApproveTestOrder"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000023"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GenerateTestCases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000024"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetTestCases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000025"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GenerateBoundaryNegativeTestCases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000026"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:AddTestCase"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000027"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:UpdateTestCase"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000028"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:DeleteTestCase"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000029"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetExecutionEnvironments"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000030"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:AddExecutionEnvironment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000031"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:UpdateExecutionEnvironment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000032"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:DeleteExecutionEnvironment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000033"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:StartTestRun"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000034"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetTestRuns"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000035"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetPlans"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000036"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000037"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetCurrentSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000038"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:CancelSubscription"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000039"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetSubscriptionHistory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000040"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetPaymentTransactions"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000041"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetUsageTracking"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000042"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:CreateSubscriptionPayment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000043"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:GetPaymentIntent"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000044"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Permission",
                            Value = "Permission:CreatePayOsCheckout"
                        });
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Auth0UserId")
                        .HasColumnType("text");

                    b.Property<string>("AzureAdB2CUserId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8554266-b401-4519-9aeb-a9283053fc58",
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tinvtse@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "TINVTSE@GMAIL.COM",
                            NormalizedUserName = "TINVTSE@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPfBZpUxae9Dzcv3f2lA5qOYSbJhxh5oYiVhS+j9Q7Rppm2ETqZUaEhWsOYisFocEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "VVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "tinvtse@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d9665377-c512-5620-0bfc-b0394064gd69",
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDlFqrwIpQDVVwXus3MatUkO1o3wq0iBqGqnXu5DkliD+ic2jmEAvoCCLoonjCzPdA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "XYZPCRDAS3MJWQD5CSW2GWPRADBXEZIN",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        });
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "System Administrator",
                            Timezone = "Asia/Ho_Chi_Minh",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("TokenName")
                        .HasColumnType("text");

                    b.Property<string>("TokenValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "identity");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.PasswordHistory", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.RoleClaim", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserClaim", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserLogin", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserProfile", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ClassifiedAds.Modules.Identity.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserRole", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.UserToken", b =>
                {
                    b.HasOne("ClassifiedAds.Modules.Identity.Entities.User", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.Role", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ClassifiedAds.Modules.Identity.Entities.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Profile");

                    b.Navigation("Tokens");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
