using ClassifiedAds.Domain.Entities;
using System;
using System.Collections.Generic;

namespace ClassifiedAds.Modules.TestGeneration.Entities;

/// <summary>
/// A structured clarification question generated by LLM from an ambiguity in an SrsRequirement.
/// Enables a guided Q&amp;A loop between the LLM and the user to resolve unclear requirements
/// before test case generation begins.
///
/// Flow:
///   Phase 1 (initial analysis) → LLM flags ambiguities → SrsRequirementClarification records created
///   FE-18C (Review Gate)       → User answers each question
///   Phase 1.5 (refinement)     → LLM re-analyzes requirement + answers → higher ConfidenceScore
/// </summary>
public class SrsRequirementClarification : Entity<Guid>, IAggregateRoot
{
    /// <summary>
    /// The requirement this clarification belongs to.
    /// </summary>
    public Guid SrsRequirementId { get; set; }

    /// <summary>
    /// The ambiguity text from Phase 1 that triggered this question.
    /// e.g. "unclear: is age validated server-side or client-side?"
    /// </summary>
    public string AmbiguitySource { get; set; }

    /// <summary>
    /// The clarification question generated by LLM for the user.
    /// e.g. "Does password 'Admin@123' imply complexity rules? Please specify."
    /// </summary>
    public string Question { get; set; }

    /// <summary>
    /// JSON array of suggested answer options LLM generated (optional).
    /// Schema: ["At least 1 uppercase + 1 number + 1 special char", "No specific rules", "Custom: ..."]
    /// Stored as jsonb. Null when LLM could not suggest options.
    /// </summary>
    public string SuggestedOptions { get; set; }

    /// <summary>
    /// The user's answer to this clarification question (free text or one of SuggestedOptions).
    /// Null until the user responds.
    /// </summary>
    public string UserAnswer { get; set; }

    /// <summary>
    /// Whether the user has answered this question.
    /// </summary>
    public bool IsAnswered { get; set; }

    /// <summary>
    /// When the user answered.
    /// </summary>
    public DateTimeOffset? AnsweredAt { get; set; }

    /// <summary>
    /// User who answered.
    /// </summary>
    public Guid? AnsweredById { get; set; }

    /// <summary>
    /// Display order among all clarifications for this requirement.
    /// </summary>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// Whether this clarification is critical — must be answered before generate is allowed.
    /// Derived from the parent ambiguity priority set by LLM.
    /// </summary>
    public bool IsCritical { get; set; }

    // Navigation property
    public SrsRequirement SrsRequirement { get; set; }
}
